openapi: 3.0.3

info:
  title: SITMUN 3 - API de Configuración y Autorización
  description: |-
    La **API de Configuración y Autorización** expone vía una API Web mecanismos para obtener una configuración 
    derivada del estado actual de los objetos de dominio en función de la identidad y rol del que solicita
    la información. Esta API se ha creado para que los **visores de mapas** y el **proxy** puedan configurarse.
        
    La **API de Configuración y Autorización** se compone de dos tipos de endpoints:
    - **Configuración y Autorización de Visor de mapas**. La petición pueden autenticarse usando un esquema de 
      *autenticación por portador* 
      (*[Bearer authentication](https://swagger.io/docs/specification/authentication/bearer-authentication/)*)
      usando un token que se ha obtenido previamente mediante la **API de Autenticación**.
      Si no se autentica, se asume que la petición se ha realizado por un usuario
      que en el dominio de SITMUN se denomina *usuario público*.
    - **Configuración y Autorización de Proxy**. La petición debe autenticarse usando una 
      [API key](https://swagger.io/docs/specification/authentication/api-keys/) enviada mediante
      la cabecera denominada `X-SITMUN-Proxy-Key`.
      El uso de una API key específica para el endpoint  **Configuración y Autorización de Proxy** es una decisión de 
      seguridad. Evita que a un cliente malicioso le pueda bastar el uso del token obtenido de la 
      **API de Autenticación** para obtener secretos vía el endpoint **Configuración y Autorización de Proxy**.

    ---

    #### La documentación de esta API está en desarrollo 

    El contenido de **Configuración y Autorización de Proxy** seguirá mejorando (aunque serán cambios menores) 
    en los próximos días para ayudar a los desarrolladores que están trabajando en el proyecto SITMUN.
    
    **Configuración y Autorización de Visor de mapas** está en proceso de definición.
    
    ---

  license:
    name: EUPL 1.2
    url: https://raw.githubusercontent.com/sitmun/sitmun-backend-core/master/LICENSE
  version: 0.8.0

tags:
  - name: Configuración y Autorización de Proxy
    description: API de Configuración y Autorización de Proxy.

  - name: Configuración y Autorización de Visor de mapas
    description: API de Configuración y Autorización de Visor de mapas (**En desarrollo**).

paths:

  /api/config/client/territory:
    get:
      tags:
        -  Configuración y Autorización de Visor de mapas
      summary: |-
        Aplicaciones para un visor de mapas.
      description: |-
        Este enpoint devuelve las aplicaciones que el visor de mapas puede mostrar.

        La petición pueden autenticarse usando un esquema de 
        *autenticación por portador* 
        (*[Bearer authentication](https://swagger.io/docs/specification/authentication/bearer-authentication/)*)
        usando un token que se ha obtenido previamente mediante la **API de Autenticación**.
        Si no se autentica, se asume que la petición se ha realizado por un usuario
        que en el dominio de SITMUN se denomina *usuario público*.
      operationId: clientTerritoryConfig
      security:
        - bearerAuth: []
      parameters:
        - name: size
          in: query
          description: Tamaño de la página solicitada.
          required: false
          schema:
            type: string
            default: 100000
        - name: page
          in: query
          description: Número de página.
          required: false
          schema:
            type: string
            default: 0
      responses:
        '200':
          description: |-
            Listado de las Aplicaciones SITMUN disponibles por el visor de mapas.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    description: Lista de aplicaciones disponibles.
                    type: array
                    items:
                      $ref: '#/components/schemas/Application'
                  totalPages:
                    description: Número total de páginas.
                    type: integer
                    format: int32
                  size:
                    description: Tamaño de la página.
                    type: integer
                    format: int32
                  number:
                    description: Número de página.
                    type: integer
                    format: int32
        '401':
          description: |-
            El cliente identificado por *autenticación por portador* no esta autorizado para 
            realizar la petición.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/config/proxy:
    post:
      tags:
        -  Configuración y Autorización de Proxy
      summary: |-
        Obtiene la configuración para una petición de un cliente realizada 
        a través del proxy.
      description: |-
        En este versión este endpoint debería poder devolver la configuración para:
        - GetMap a un OGC WMS.
        - SELECT a una base de datos.
        
        La petición debe autenticarse usando una 
        [API key](https://swagger.io/docs/specification/authentication/api-keys/) enviada mediante
        la cabecera denominada `X-SITMUN-Proxy-Key`.
      operationId: proxyConfig
      security:
        - proxyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProxyConfigurationRequest'
        required: true
      responses:
        '200':
          description: |-
            Configuración a aplicar por el proxy para crear una petición
            a un servicio web remoto o a una base de datos a partir de la
            petición recibida por el cliente.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/OgcWmsConfiguration'
                  - $ref: '#/components/schemas/DatasourceConfiguration'
                discriminator:
                  propertyName: type
                  mapping:
                    "ogc:wms": '#/components/schemas/OgcWmsConfiguration'
                    "datasource": '#/components/schemas/DatasourceConfiguration'
        '401':
          description: |-
            Representa dos casos:

            - El proxy no está autorizado para realizar la petición.
            - El cliente identificado por `id_token` no esta autorizado para 
              realizar la petición.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:

    JSONWebToken:
      description: "JSON Web Token"
      type: string
      pattern: ^([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_\-\+\/=]+)$
      example: "eyJhbGciOiJ..."

    ProxyConfigurationRequest:
      description: Parámetros de la petición realizada por el visor de mapas al proxy.
      type: object
      properties:
        appId:
          type: string
          description: Identificador de la aplicación.
        terId:
          type: string
          description: Identificador del territorio.
        type:
          type: string
          description: Identificador del tipo de servicio.
        typeId:
          type: string
          description: Identificador del servicio.
        method:
          type: string
          enum: [ GET, POST ]
          description: Método HTTP empleado.
        parameters:
          type: object
          additionalProperties: true
          description: Mapa con los parámetros pasados en la pregunta.
        requestBody:
          type: object
          additionalProperties: true
          description: Mapa con los parámetros pasados en el cuerpo de la petición.
        id_token:
          $ref: "#/components/schemas/JSONWebToken"
      required:
        - appId
        - terId
        - type
        - typeId
        - method

    Configuration:
      type: object
      description: Configuración de una petición
      properties:
        type:
          type: string
          description: Tipo de configuración devuelta.
        exp:
          type: integer
          description: |-
            Fecha de expiración de la configuración expresado en segundos desde
            1970-01-01T00:00:00Z UTC. La configuración se puede usar solo hasta
            antes de dicha fecha.
        vary:
          description: |-
            Esta configuración está originada por una determinada
            petición del cliente. Si hay una nueva petición del cliente
            que se diferencia sólo en los valores asociados a los 
            `parameters` listados en `vary`, se debe reutilizar esta 
            configuración en lugar de solicitar una nueva si no ha expirado.
          type: array
          items:
            type: string
        payload:
          type: object
          additionalProperties: true
          description: Valores de la configuración.
      required:
        - type
        - exp
        - payload

    OgcWmsConfiguration:
      type: object
      description: Configuración de una petición a un servicio remoto OGC WMS.
      allOf:
        - $ref: "#/components/schemas/Configuration"
        - type: object
          properties:
            payload:
              type: object
              properties:
                uri:
                  type: string
                  format: uri
                method:
                  type: string
                  enum: [ GET ]
                  description: Método HTTP empleado.
                parameters:
                  type: object
                  additionalProperties: true
                  description: Mapa con los parámetros pasados en la pregunta.
                security:
                  description: Mecanismo de autenticación
                  oneOf:
                    - $ref: "#/components/schemas/HttpSecurityScheme"
              required:
                - uri
                - method

    SecurityScheme:
      type: object
      description: Esquema de autenticación.
      properties:
        type:
          description: Identificador del esquema de autenticación.
          type: string
      required:
        - type

    HttpSecurityScheme:
      type: object
      description: Esquema de autenticación HTTP.
      allOf:
        - $ref: "#/components/schemas/SecurityScheme"
        - type: object
          properties:
            type:
              description: Esquema tipo autenticación HTTP.
              type: string
              enum: [ "http" ]
            scheme:
              description: Esquema HTTP Basic.
              type: string
              enum: [ "basic" ]
            username:
              description: Nombre de usuario.
              type: string
            password:
              description: Contraseña.
              type: string
              format: password
          required:
            - type
            - scheme
            - username
            - password

    DatasourceConfiguration:
      type: object
      description: Configuración de una petición a una base de datos JDBC.
      allOf:
        - $ref: "#/components/schemas/Configuration"
        - type: object
          properties:
            payload:
              properties:
                uri:
                  description: URI de conexión a una base de datos JDBC.
                  type: string
                  format: uri
                user:
                  description: Nombre de usuario.
                  type: string
                password:
                  description: Contraseña.
                  type: string
                  format: password
                driver:
                  description: Nombre completo del driver JDBC.
                  type: string
                sql:
                  description: Sentencia SQL que se debe ejecutar.
                  type: string
              required:
                - uri
                - user
                - password
                - driver
                - sql

    Application:
      type: object
      description: Aplicación de SITMUN.
      properties:
        id:
          type: string
          description: Identificador de la aplicación.
        title:
          type: string
          description: Nombre de la aplicación.

    ErrorResponse:
      type: object
      description: Respuesta que puede acompañar a un error.
      properties:
        status:
          type: integer
          description: Código de estado HTTP.
        error:
          type: string
          description: Descripción del código de error.
        message:
          type: string
          description:  Mensaje descriptivo del error.
        path:
          type: string
          description: API afectado.
        timestamp:
          type: string
          format: date-time
          description: Marca de tiempo
      required:
        - status
        - error
        - message
        - path
        - timestamp

  securitySchemes:
    proxyAuth:
      type: apiKey
      in: header
      name: X-SITMUN-Proxy-Key

