# =====================================================================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# Database properties for production (spring.datasource) are defined elsewhere.
#
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =====================================================================================================================

logging:
  level:
    ROOT: INFO
    org.sitmun.plugin.core: INFO

management:
  metrics:
    enable:
      all: false
      sitmun: true
  endpoints:
    web:
      base-path: /api/dashboard

spring:
  jackson:
    serialization:
      indent-output: true
  jpa:
    show-sql: false
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    contexts: prod
    run-async: false
    sync-legacy: false
    on-startup-update: false

server:
  port: 8080

security:
  authentication:
    jwt:
      secret: 9ef80c644166846897f6a87d3cf6ab204d144229
      token-validity-in-miliseconds: 36000000

# ===================================================================
# SITMUN specific properties
# ===================================================================

sitmun:
  dashboard:
    fetchMetrics: 60000
    initialDelay: 60000
    cartographies-by-created-date.size: 30 #last days
    users-by-created-date.size: 30 # last days
    users-per-application.size: 30 # last days
  proxy:
    config-response-validity-in-seconds: 3600
