# =====================================================================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =====================================================================================================================

sitmun:
  dashboard:
    fetchMetrics: 86400000
    initialDelay: 120000
    cartographies-by-created-date.size: 30 #last days
    users-by-created-date.size: 30 # last days
    users-per-application.size: 30 # last days

logging:
  level:
    ROOT: INFO
    org.sitmun.plugin.core: INFO

management:
  metrics:
    enable:
      all: false
      sitmun: true
  endpoints:
    web:
      base-path: /api/dashboard

spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./build/sitmundb
    username: sample
    password:
    hikari:
      poolName: Hikari
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    open-in-view: true    # This must be false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    contexts: dev
    run-async: true
    sync-legacy: true

security:
  authentication:
    jwt:
      secret: 9ef80c644166846897f6a87d3cf6ab204d144229
      token-validity-in-miliseconds: 36000000
    middleware:
      secret: 9ef80c644166846897f6a87d3cf6ab204d144229

server:
  port: 8080

springdoc:
  swagger-ui:
    url: /v3/api-docs.yaml
  api-docs:
    enabled: false

# ===================================================================
# SITMUN specific properties
# ===================================================================
