language: java

jdk:  
  - openjdk8

addons:
  sonarcloud:
    organization: sitmun

env:
  - SPRING_PROFILES_ACTIVE=dev

script: ./build-scripts/script.sh

after_success:
  # SonarCloud require analysis to be run on at least Java 11
  # Xenial has pre-installed openjdk11
  - jdk_switcher use openjdk11
  - ./build-scripts/after_success.sh
  # Back to Java 8
  - jdk_switcher use openjdk8
  - ./build-scripts/deploy_docs.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache
    - $HOME/.m2/repository
    - .gradle
    - node_modules
    
deploy:
  provider: script
  script: bash ./build-scripts/deploy.sh
  on:
    tags: true

# Safelist. The regular expression allows for tagged commits that match it to be built
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
