services:
  backend:
    build: .
    ports:
      - "9001:8080"
    depends_on:
      - persistence
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL:-jdbc:postgresql://persistence:5432/}${DATABASE:-sitmun3}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME:-sitmun3}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD:-sitmun3}
      - SITMUN_PROXY_FORCE=${FORCE_USE_OF_PROXY:-true}
      - SITMUN_PROXY_URL=http://localhost:9000/middleware
      - SECURITY_AUTHENTICATION_MIDDLEWARE_SECRET=9ef80c644166846897f6a87d3cf6ab204d144229
    volumes:
      - ${BACKEND_CONFIG_DIR:-./env/heroku/resources/config}:/usr/src/config
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/dashboard/health"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3

  persistence:
    image: postgres:16-alpine
    restart: always
    ports:
      - "9003:5432"
    environment:
      POSTGRES_DB: ${DATABASE:-sitmun3}
      POSTGRES_USER: ${DATABASE_USERNAME:-sitmun3}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-sitmun3}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME:-sitmun3}"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3

volumes:
  pgdata:
