# =====================================================================================================================
# Spring Boot configuration for the "openapi" profile.
#
# This configuration overrides the application.yml file.
#
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =====================================================================================================================

springdoc:
  api-docs:
    enabled: true

# ===================================================================
# SITMUN specific properties
# ===================================================================
