# =====================================================================================================================
# Spring Boot configuration for the "diba" profile.
#
# This configuration overrides the application.yml file.
#
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =====================================================================================================================

# ===================================================================
# SITMUN specific properties
# ===================================================================

default:
  territory:
    name: Diputació de Barcelona
