# =====================================================================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =====================================================================================================================

server:
  port: 8080 # Configure the port used by the application
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:32768/FREE # Configure the connection URL
    username: c##stm3 # Configure the username
    password: stm3 # Configure the password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  jackson:
    serialization:
      indent-output: true
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

security:
  authentication:
    jwt:
      secret: 9ef80c644166846897f6a87d3cf6ab204d144229
      token-validity-in-miliseconds: 36000000
    middleware:
      secret: 9ef80c644166846897f6a87d3cf6ab204d144229
    ldap:
      host: ldap://localhost:1389
      base_dn: dc=example,dc=com
      user_dn_pattern: uid={0}
      user_ldap: cn=admin
      password_ldap: admin

logging:
  level:
    ROOT: INFO
    org.sitmun.plugin.core: INFO

management:
  metrics:
    enable:
      all: false
      sitmun: true
  endpoints:
    web:
      base-path: /api/dashboard

# ===================================================================
# SITMUN specific properties
# ===================================================================

sitmun:
  dashboard:
    fetchMetrics: 60000
    initialDelay: 60000
    cartographies-by-created-date.size: 30 #last days
    users-by-created-date.size: 30 # last days
    users-per-application.size: 30 # last days
  proxy:
    config-response-validity-in-seconds: 3600

