version: "3"
services:
  oracle:
    image: oracle/database:11.2.0.2-xe
    container_name: oracle-db
    shm_size: "1gb"
    ports:
      - "9080:8080"
      - "1521:1521"
    environment:
      - ORACLE_PWD=password
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./oracle/scripts/setup:/u01/app/oracle/scripts/setup