version: '3'
services:
  admin:
    image: sitmun/admin
    build:
      context: ./admin
      args:
        BASE_HREF: http://localhost:8080/
    ports:
      - 8080:8080
    depends_on:
      - backend
  backend:
    image: sitmun/backend
    build:
      context: ./backend
      args:
        GRADLE_BUILD_TASK: :deploy:postgres:build -x test
        GRADLE_BUILD_OUTPUT: deploy/postgres/build/libs/postgres-0.8.0-SNAPSHOT.jar
    environment:
      SPRING_PROFILES_ACTIVE: dev,postgres
      spring.datasource.url: jdbc:postgresql://postgres:5432/stm3
      spring.datasource.username: stm3
      spring.datasource.password: stm3
      spring.datasource.hikari.auto-commit: false
      spring.jpa.properties.hibernate.dialect: org.sitmun.common.tools.PostgresSQL93DialectFixed
      spring.liquibase.run-async: true
      server.forward-headers-strategy: framework
      security.authentication.jwt.secret: 9ef80c644166846897f6a87d3cf6ab204d144229
      TZ: CET
    depends_on:
      - postgres
  postgres:
    image: postgres:9.3-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: stm3
      POSTGRES_USER: stm3
    volumes:
      - ./postgres/scripts/:/docker-entrypoint-initdb.d