databaseChangeLog:
  - changeSet:
      id: 3
      author: sitmun
      context: dev
      changes:
        - loadData:
            encoding: UTF-8
            file: 03_initial_data_dev_user_configuration.csv
            relativeToChangelogFile: true
            separator: ;
            tableName: STM_USR_CONF
            usePreparedStatements: true
        - sql:
            sql: INSERT INTO STM_SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('UCO_ID', 10000);

