databaseChangeLog:
  - changeSet:
      id: 5
      author: sitmun
      context: dev
      changes:
        - loadData:
            encoding: UTF-8
            file: 05_translations/STM_LANGUAGE.csv
            relativeToChangelogFile: true
            tableName: STM_LANGUAGE
            columns:
              - column:
                  name: LAN_ID
                  type: NUMERIC
              - column:
                  name: LAN_SHORTNAME
                  type: STRING
              - column:
                  name: LAN_NAME
                  type: STRING
        - sql:
            sql: INSERT INTO STM_SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('LAN_ID', 5);
        - loadData:
            encoding: UTF-8
            file: 05_translations/STM_TRANSLATION_ES.csv
            relativeToChangelogFile: true
            tableName: STM_TRANSLATION
            columns:
              - column:
                  name: TRA_ID
                  type: NUMERIC
              - column:
                  name: TRA_ELEID
                  type: NUMERIC
              - column:
                  name: TRA_COLUMN
                  type: STRING
              - column:
                  name: TRA_LANID
                  type: NUMERIC
              - column:
                  name: TRA_NAME
                  type: STRING
        - loadData:
            encoding: UTF-8
            file: 05_translations/STM_TRANSLATION_CA.csv
            relativeToChangelogFile: true
            tableName: STM_TRANSLATION
            columns:
              - column:
                  name: TRA_ID
                  type: NUMERIC
              - column:
                  name: TRA_ELEID
                  type: NUMERIC
              - column:
                  name: TRA_COLUMN
                  type: STRING
              - column:
                  name: TRA_LANID
                  type: NUMERIC
              - column:
                  name: TRA_NAME
                  type: STRING
        - loadData:
            encoding: UTF-8
            file: 05_translations/STM_TRANSLATION_OC.csv
            relativeToChangelogFile: true
            tableName: STM_TRANSLATION
            columns:
              - column:
                  name: TRA_ID
                  type: NUMERIC
              - column:
                  name: TRA_ELEID
                  type: NUMERIC
              - column:
                  name: TRA_COLUMN
                  type: STRING
              - column:
                  name: TRA_LANID
                  type: NUMERIC
              - column:
                  name: TRA_NAME
                  type: STRING
        - loadData:
            encoding: UTF-8
            file: 05_translations/STM_TRANSLATION_FR.csv
            relativeToChangelogFile: true
            tableName: STM_TRANSLATION
            columns:
              - column:
                  name: TRA_ID
                  type: NUMERIC
              - column:
                  name: TRA_ELEID
                  type: NUMERIC
              - column:
                  name: TRA_COLUMN
                  type: STRING
              - column:
                  name: TRA_LANID
                  type: NUMERIC
              - column:
                  name: TRA_NAME
                  type: STRING
        - sql:
            sql: INSERT INTO STM_SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('TRA_ID', 600000);
