name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: dev

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Deploy to Heroku
        env:
          HEROKU_EMAIL: ${{secrets.HEROKU_EMAIL}}
          HEROKU_TOKEN: ${{secrets.HEROKU_TOKEN}}
        run: |
          cat <<EOF >~/.netrc
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_TOKEN
          EOF
          git config --global user.name "Automated Heroku Deploy"
          git config --global user.email $HEROKU_EMAIL
          git remote add heroku https://git.heroku.com/sitmun-backend-core.git
          git push heroku master
